Models/Diary.cs
using System;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
namespace csharp_diary.Models
{
    public class Diary
    {
        public int ID { get; set; }
        public String EntryTitle { get; set; }
        public String EntiryDesc { get; set; }
        public Diary()
        {
            EntryDate = DateTime.Today;

        }
        public DateTime EntryDate { get; set; }
        public string Owner { get; set; }
        // public string UserID { get; set; }
        // [ForeignKey("UserID")]
        // public virtual ApplicationUser ApplicationUser { get; set; }
    }

    public class DiaryContext : DbContext
    {
        DbSet<Diary> Diaries { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=localhost,1433; Database=Test;User=sa; Password=your_password; TrustServerCertificate=True");
        }
    }
}

Models/ErrorViewModel.cs
namespace csharp_diary.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/DiaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

using csharp_diary.Data;
using csharp_diary.Models;

namespace csharp_diary.Controllers
{
    public class DiaryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DiaryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Diary
        public async Task<IActionResult> Index()
        {
            return _context.Diary != null ?
                        View(await _context.Diary.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Diary'  is null.");
        }

        // GET: Diary/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Diary == null)
            {
                return NotFound();
            }

            var diary = await _context.Diary
                .FirstOrDefaultAsync(m => m.ID == id);
            if (diary == null)
            {
                return NotFound();
            }

            return View(diary);
        }

        // GET: Diary/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Diary/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,EntryTitle,EntiryDesc,EntryDate")] Diary diary)
        {
            if (ModelState.IsValid)
            {
                // var owner = User.Identity?.Name;
                // diary.Owner = owner
                _context.Add(diary);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(diary);
        }

        // GET: Diary/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Diary == null)
            {
                return NotFound();
            }

            var diary = await _context.Diary.FindAsync(id);
            if (diary == null)
            {
                return NotFound();
            }
            return View(diary);
        }

        // POST: Diary/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,EntryTitle,EntiryDesc,EntryDate")] Diary diary)
        {
            if (id != diary.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(diary);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DiaryExists(diary.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(diary);
        }

        // GET: Diary/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Diary == null)
            {
                return NotFound();
            }

            var diary = await _context.Diary
                .FirstOrDefaultAsync(m => m.ID == id);
            if (diary == null)
            {
                return NotFound();
            }

            return View(diary);
        }

        // POST: Diary/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Diary == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Diary'  is null.");
            }
            var diary = await _context.Diary.FindAsync(id);
            if (diary != null)
            {
                _context.Diary.Remove(diary);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DiaryExists(int id)
        {
            return (_context.Diary?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using csharp_diary.Models;

namespace csharp_diary.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Diary/Create.cshtml
@model csharp_diary.Models.Diary

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Diary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EntryTitle" class="control-label"></label>
                <input asp-for="EntryTitle" class="form-control" />
                <span asp-validation-for="EntryTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntiryDesc" class="control-label"></label>
                <input asp-for="EntiryDesc" class="form-control" />
                <span asp-validation-for="EntiryDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryDate" class="control-label"></label>
                <input asp-for="EntryDate" class="form-control" />
                <span asp-validation-for="EntryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Diary/Delete.cshtml
@model csharp_diary.Models.Diary

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Diary</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntiryDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntiryDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Diary/Details.cshtml
@model csharp_diary.Models.Diary

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Diary</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntiryDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntiryDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntryDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntryDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Diary/Edit.cshtml
@model csharp_diary.Models.Diary

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Diary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="EntryTitle" class="control-label"></label>
                <input asp-for="EntryTitle" class="form-control" />
                <span asp-validation-for="EntryTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntiryDesc" class="control-label"></label>
                <input asp-for="EntiryDesc" class="form-control" />
                <span asp-validation-for="EntiryDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryDate" class="control-label"></label>
                <input asp-for="EntryDate" class="form-control" />
                <span asp-validation-for="EntryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Diary/Index.cshtml
@model IEnumerable<csharp_diary.Models.Diary>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Index";
}
<div class="d-flex flex-column justify-content-center">
    @if (SignInManager.IsSignedIn(User))
    {
        <p> Hello @User.Identity?.Name!</p>
    }
    <h1 class="text-center">Your Diary</h1>
    <p>This is your diary, when creating a new entry, write down what you're feeling</p>
</div>


<div id="diaryEntryContainer" class="d-flex flex-wrap justify-content-center">
    @foreach (var item in Model)
    {
        <div class="card m-2" style="width 18rem;">
            <div class="card-header" style="width auto">
                <h2>@Html.DisplayFor(modelItem => item.EntryTitle)</h2>
                <h5>@Html.DisplayFor(modelItem => item.EntryDate)</h5>
            </div>
            <div class="card-body">
                <p>
                    @Html.DisplayFor(modelItem => item.EntiryDesc)
                </p>
            </div>
            <div class="d-flex" style="justify-content: space-evenly;">
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.ID">Edit</a>
                <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.ID">Details</a>
                <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </div>
        </div>
    }
</div>
<p class="d-flex justify-content-center">
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My Diary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet"  href="../EmptyCSSFile/css" asp-append-version="true" />
    @*<link rel="stylesheet" href="index.css" asp-append-version="true" />*@
    @* <link rel="stylesheet" href="~/csharp_diary.styles.css"
        asp-append-version="true" /> *@
</head>

<body>
    <header>
        <nav class=" navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My Diary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Diary"
                                asp-action="Index">Diary</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="background-image: url(../assets/images/homebg);">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" border-top footer text-muted">
        <div class="container">
            &copy; 2022 - csharp_diary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>